# Generated by Django 3.2.8 on 2021-10-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_request', models.CharField(max_length=50)),
                ('db_answer', models.CharField(max_length=50)),
            ],
        ),
    ]
