# Generated by Django 3.2.8 on 2021-10-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbrequest',
            name='db_answer',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dbrequest',
            name='db_request',
            field=models.CharField(max_length=250),
        ),
    ]
