# Generated by Django 3.2.8 on 2021-10-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbserver', '0002_auto_20211016_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DbRequest',
            new_name='AST',
        ),
    ]
