# Generated by Django 3.2.8 on 2021-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbserver', '0003_rename_dbrequest_ast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ast',
            name='id',
        ),
        migrations.AddField(
            model_name='ast',
            name='db_index',
            field=models.CharField(default=123, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
