# Generated by Django 3.2.8 on 2021-10-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbserver', '0004_auto_20211016_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='ast',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ast',
            name='db_index',
            field=models.CharField(max_length=10),
        ),
    ]
