# Generated by Django 3.2.8 on 2021-10-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbserver', '0005_auto_20211016_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ast',
            name='db_index',
        ),
    ]
