# Generated by Django 3.2.8 on 2021-10-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbserver', '0007_ast_db_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ast',
            name='db_index',
            field=models.CharField(max_length=10),
        ),
    ]
