# Generated by Django 3.2.8 on 2021-10-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbserver', '0008_alter_ast_db_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ast',
            old_name='db_index',
            new_name='db_id',
        ),
    ]
