# Generated by Django 3.2.8 on 2021-10-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbserver', '0010_remove_ast_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ast',
            name='db_index',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
