# Generated by Django 3.2.8 on 2021-10-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbserver', '0011_ast_db_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_index', models.CharField(max_length=10)),
                ('db_request', models.CharField(max_length=250)),
                ('db_answer', models.CharField(max_length=250)),
            ],
        ),
    ]
