version: "3.3"

services:

  postgres:
    container_name: "postgres_container"
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "BoBSDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  mssql:
    container_name: "mssql_container"
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret1234
    ports:
      - "1433:1433"

  app:
    container_name: "app_container"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
