version: "3.3"

services:

  db:
    container_name: "postgres_container"
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  app:
    container_name: "app_container"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
