version: "3.3"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  app:
    container_name: app_container
    build:
      dockerfile: Dockerfile
      ports:
        - "8000:8000"
